---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: belimo-db
  labels:
    app: belimo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: belimo-db
  template:
    metadata:
      labels:
        app: belimo-db
    spec:
      containers:
      - name: belimo-db
        image: mysql:5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "my-secret-pw"
        - name: MYSQL_DATABASE
          value: "josef"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: belimo-db
spec:
  selector:
    app: belimo-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: belimo-backend
  labels:
    app: belimo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: belimo-backend
  template:
    metadata:
      labels:
        app: belimo-backend
    spec:
      containers:
      - name: belimo-backend
        image: robertbrem/belimo-backend:todo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: belimo-backend
spec:
  selector:
    app: belimo-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31081
  type: NodePort
